/**
 * Bundled EasyList-style filter list for Next Token's native ad blocker.
 *
 * This is a compact, curated subset (a few hundred domain rules) covering
 * the most common ad servers, trackers, and analytics beacons. It ships
 * INSIDE the app — no remote list is ever fetched at runtime.
 *
 * Syntax subset supported by src/main/adblock/matcher.ts:
 *   ! comment            [ comment section
 *   ||domain^            domain-anchored (domain + subdomains)
 *   |prefix / suffix|    anchored rules
 *   *                    wildcard, ^ = separator placeholder
 *   @@rule               exception (allow) rule
 *   $opt1,opt2           options: third-party, ~third-party, first-party,
 *                        domain=a.com|~b.com, resource types
 *                        (script, image, stylesheet, font, media, object,
 *                        xmlhttprequest, subdocument, websocket, ping, other)
 */
export const FILTER_TEXT = `! Next Token bundled filters — ad servers
||doubleclick.net^
||googlesyndication.com^
||googleadservices.com^
||googletagservices.com^
||2mdn.net^
||adservice.google.com^
||ads.google.com^
||amazon-adsystem.com^
||aax.amazon-adsystem.com^
||adsrvr.org^
||adnxs.com^
||adnxs-simple.com^
||criteo.com^
||criteo.net^
||pubmatic.com^
||rubiconproject.com^
||openx.net^
||openxadexchange.com^
||casalemedia.com^
||advertising.com^
||ads-twitter.com^
||static.ads-twitter.com^
||ads-api.twitter.com^
||ads.linkedin.com^
||snap.licdn.com^
||ads.pinterest.com^
||analytics.pinterest.com^$third-party
||taboola.com^
||outbrain.com^
||revcontent.com^
||mgid.com^
||zergnet.com^
||content.ad^
||sharethrough.com^
||triplelift.com^
||bidswitch.net^
||indexww.com^
||smartadserver.com^
||adform.net^
||adform.com^
||moatads.com^
||ads.yahoo.com^
||ads.aol.com^
||ads.msn.com^
||gemini.yahoo.com^
||analytics.yahoo.com^$third-party
||adtech.de^
||adtechus.com^
||advertising.microsoft.com^
||mookie1.com^
||stickyadstv.com^
||ads.stickyadstv.com^
||lkqd.com^
||springserve.com^
||freewheel.tv^
||spotxchange.com^
||vidazoo.com^
||anyclip.com^
||primis.tech^
||connatix.com^
||aniview.com^
||avantisvideo.com^
||brid.tv^
||kargo.com^
||justpremium.com^
||highfivermedia.com^
||insticator.com^
||playwire.com^
||venatusmedia.com^
||monetizemore.com^
||snigelweb.com^
||nitropay.com^
||ezoic.com^
||ezoic.net^
||mediavine.com^
||adthrive.com^
||freestar.io^
||freestar.com^
||total-media.net^
||valueimpression.com^
||smilewanted.com^
||optad360.io^
||raptive.com^
||seedtag.com^
||teads.tv^
||jwpltx.com^
||imasdk.googleapis.com^$third-party
||adnami.io^
||dianomi.com^
||adskeeper.com^
||adblade.com^
||engageya.com^
||trafficjunky.net^
||exoclick.com^
||adcash.com^
||propellerads.com^
||popads.net^
||popcash.net^
||adsterra.com^
||hilltopads.net^
||clickadu.com^
||undertone.com^
||conversantmedia.com^
||simpli.fi^
||tapad.com^
||rlcdn.com^
||bluekai.com^
||exelator.com^
||eyeota.net^
||yieldmo.com^
||nativo.com^
||gumgum.com^
||sovrn.com^
||lijit.com^
||bidbarrel.com^
||doubleverify.com^
||iasds01.com^
||adsafeprotected.com^
||crwdcntrl.net^
||demdex.net^
||omtrdc.net^
||2o7.net^
||everesttech.net^
||agkn.com^
||mathtag.com^
||quantserve.com^
||scorecardresearch.com^
||addthis.com^
||moat.com^$third-party
! Mobile / in-app ad SDKs (also used on mobile web)
||ads.mopub.com^
||mopub.com^
||unityads.unity3d.com^
||applovin.com^
||vungle.com^
||ironsrc.com^
||supersonicads.com^
||adcolony.com^
||inmobi.com^
||smaato.net^
||fyber.com^
! Analytics & trackers
||google-analytics.com^$third-party
||googletagmanager.com^$third-party
||analytics.google.com^$third-party
||stats.g.doubleclick.net^
||connect.facebook.net^$third-party
||bat.bing.com^
||c.bing.com^
||clarity.ms^
||mc.yandex.ru^$third-party
||an.yandex.ru^
||yabs.yandex.ru^
||chartbeat.com^
||chartbeat.net^
||hotjar.com^
||hotjar.io^
||fullstory.com^
||mouseflow.com^
||crazyegg.com^
||luckyorange.com^
||mixpanel.com^
||segment.io^$third-party
||segment.com^$third-party
||amplitude.com^
||heap.io^
||pendo.io^
||optimizely.com^
||vwo.com^
||abtasty.com^
||convert.com^
||newrelic.com^
||nr-data.net^
||logrocket.com^
||inspectlet.com^
||sessioncam.com^
||clicktale.com^
||clicktale.net^
||decibelinsight.net^
||contentsquare.net^
||quantummetric.com^
||glassboxdigital.com^
||userreplay.net^
||smartlook.com^
||ptengine.com^
||monetate.net^
||evergage.com^
||certona.net^
||richrelevance.com^
||barilliance.com^
||rtbhouse.com^
||adroll.com^
||perfectaudience.com^
||retargeter.com^
||choozle.com^
||freshrelevance.com^
||bizible.com^
||demandbase.com^
||6sense.com^
||clearbit.com^
||clearbitjs.com^
||sailthru.com^
||listrakbi.com^
||bronto.com^
||emarsys.net^
||dotdigitalgroup.com^
||justuno.com^
||privy.com^
||sumome.com^
||hellobar.com^
||addshoppers.com^
! Generic script patterns (third-party only, conservative)
/matomo.js$third-party
/piwik.js$third-party
/fbevents.js$third-party
`;
